"""Add content, is_folder, parent_id to item

Revision ID: 67e16814e0c4
Revises: fe56fa70289e
Create Date: 2026-03-24 09:09:51.898524

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '67e16814e0c4'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('is_folder', sa.Boolean(), nullable=False))
    op.add_column('item', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'item', 'item', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'parent_id')
    op.drop_column('item', 'is_folder')
    op.drop_column('item', 'content')
    # ### end Alembic commands ###
