"""add published_to_community

Revision ID: 6d8ec23f34f9
Revises: f6a7b8c9d0e1
Create Date: 2026-04-15 18:37:06.273510

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d8ec23f34f9'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communitypost',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_forge_id', sa.Uuid(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communitypost_owner_id'), 'communitypost', ['owner_id'], unique=False)
    op.create_table('userfollow',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('following_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('postfavorite',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['communitypost.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('dashboard_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('dashboard_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('dashboard_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('forge', sa.Column('published_to_community', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('forge', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('forge', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    op.drop_index(op.f('forge_embedding_ivfflat_idx'), table_name='forge', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_forge_owner_id'), 'forge', ['owner_id'], unique=False)
    op.drop_constraint(op.f('forge_parent_id_fkey'), 'forge', type_='foreignkey')
    op.drop_constraint(op.f('forge_owner_id_fkey'), 'forge', type_='foreignkey')
    op.create_foreign_key(None, 'forge', 'user', ['owner_id'], ['id'])
    op.drop_column('forge', 'updated_at')
    op.drop_column('forge', 'created_at')
    op.drop_index(op.f('ix_forgelink_target_id'), table_name='forgelink')
    op.drop_constraint(op.f('forgelink_target_id_fkey'), 'forgelink', type_='foreignkey')
    op.drop_constraint(op.f('forgelink_source_id_fkey'), 'forgelink', type_='foreignkey')
    op.create_foreign_key(None, 'forgelink', 'forge', ['source_id'], ['id'])
    op.create_foreign_key(None, 'forgelink', 'forge', ['target_id'], ['id'])
    op.alter_column('user_activity_ping', 'pinged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_user_activity_ping_pinged_at'), table_name='user_activity_ping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_activity_ping_pinged_at'), 'user_activity_ping', ['pinged_at'], unique=False)
    op.alter_column('user_activity_ping', 'pinged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'forgelink', type_='foreignkey')
    op.drop_constraint(None, 'forgelink', type_='foreignkey')
    op.create_foreign_key(op.f('forgelink_source_id_fkey'), 'forgelink', 'forge', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('forgelink_target_id_fkey'), 'forgelink', 'forge', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_forgelink_target_id'), 'forgelink', ['target_id'], unique=False)
    op.add_column('forge', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('forge', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'forge', type_='foreignkey')
    op.create_foreign_key(op.f('forge_owner_id_fkey'), 'forge', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('forge_parent_id_fkey'), 'forge', 'forge', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_forge_owner_id'), table_name='forge')
    op.create_index(op.f('forge_embedding_ivfflat_idx'), 'forge', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('forge', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('forge', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('forge', 'published_to_community')
    op.alter_column('dashboard_task', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dashboard_task', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('dashboard_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_table('postfavorite')
    op.drop_table('userfollow')
    op.drop_index(op.f('ix_communitypost_owner_id'), table_name='communitypost')
    op.drop_table('communitypost')
    # ### end Alembic commands ###
